1.5.5
* New home dir structure
* Refactoring
* Docs

diff --git a/arch-os b/arch-os
--- a/arch-os
+++ b/arch-os
@@ -8,44 +8,22 @@ set -Eeo pipefail # Set script error handling
 # ///////////////////////////////////////////////////////////////////
 
 # VERSION
-VERSION="1.5.4"
+VERSION="1.5.5"
 
 # HOME
 ARCH_OS_HOME="${HOME}/.arch-os"
-ARCH_OS_CONF="${ARCH_OS_HOME}/arch-os.conf"
-KITTY_CONF="${ARCH_OS_HOME}/kitty.conf"
-PACKAGES_DB="${ARCH_OS_HOME}/packages.db"
-NEWS_DB="${ARCH_OS_HOME}/news.db"
+ARCH_OS_CONF="${ARCH_OS_HOME}/settings.conf"
+KITTY_CONF="${ARCH_OS_HOME}/config/kitty.conf"
+PACKAGES_DB="${ARCH_OS_HOME}/database/packages.db"
+NEWS_DB="${ARCH_OS_HOME}/database/news.db"
 
 # COLORS
-# https://github.com/muesli/termenv?tab=readme-ov-file#color-chart
+# Color chart: https://github.com/muesli/termenv?tab=readme-ov-file#color-chart
+COLOR_PURPLE=212
 COLOR_WHITE=7
 COLOR_GREEN=2
-COLOR_PURPLE=212
 COLOR_YELLOW=3
 COLOR_RED=1
-
-# ///////////////////////////////////////////////////////////////////
-# TRAPS
-# ///////////////////////////////////////////////////////////////////
-
-# RETURN CODES
-#   0 : success (default)
-#   1 : fatal   (uncatched)
-#   2 : error   (catched)
-#   3 : exit    (user)
-# 130 : exit    (user)
-
-trap_exit() {
-    rm -f "${ARCH_OS_HOME}/.mirrorlist.tmp"
-    [ "$1" != "3" ] && [ "$1" != "130" ] && gum_confirm --affirmative 'Quit' --negative '' ''
-    clear && return "$1"
-}
-
-trap_error() {
-    [ "$1" != "2" ] && [ "$1" != "3" ] && [ "$1" != "130" ] && gum_fail "${BASH_COMMAND} failed ($1) in function '${2}' (line ${3})"
-    return "$1"
-}
 
 # ///////////////////////////////////////////////////////////////////
 # MAIN
@@ -57,8 +35,8 @@ main() {
     local user_input options selected_action skip_confirm first_run
 
     # Check dependencies
-    if ! command -v /usr/bin/kitty &>/dev/null; then echo "ERROR: kitty not found. Install with: sudo pacman -S kitty" >&2 && exit 1; fi
     if ! command -v /usr/bin/gum &>/dev/null; then echo "ERROR: gum not found. Install with: sudo pacman -S gum" >&2 && exit 1; fi
+    if ! command -v /usr/bin/kitty &>/dev/null; then echo "ERROR: kitty not found. Install with: sudo pacman -S kitty" >&2 && exit 1; fi
     if ! command -v /usr/bin/checkupdates &>/dev/null; then echo "ERROR: checkupdates not found. Install with: sudo pacman -S pacman-contrib" >&2 && exit 1; fi
     if ! command -v /usr/bin/notify-send &>/dev/null; then echo "ERROR: notify-send not found. Install with: sudo pacman -S libnotify" >&2 && exit 1; fi
 
@@ -75,7 +53,7 @@ main() {
         fi
     fi
 
-    # Check arguments
+    # Check number of arguments
     if [ $# -gt 1 ]; then
         print_header && action_help && echo && gum_fail "Max. 1 argument supported!"
         gum_confirm --affirmative "Quit" --negative '' ''
@@ -94,8 +72,8 @@ main() {
         update_result="$(action_check_updates_available)"
         update_count=$(echo "$update_result" | wc -l)
         if [ "$update_count" -gt 0 ]; then
-            [ "$update_count" = 1 ] && update_txt="${update_count} new Update available"
-            [ "$update_count" -gt 1 ] && update_txt="${update_count} new Updates available"
+            [ "$update_count" = 1 ] && update_txt="${update_count} Update available"
+            [ "$update_count" -gt 1 ] && update_txt="${update_count} Updates available"
             notify-send --app-name "Arch OS Manager" -i "${WORKING_DIR}/docs/logo.svg" "System Upgrade" "$update_txt"
             echo "$update_result"
         fi
@@ -169,13 +147,43 @@ main() {
 }
 
 # ///////////////////////////////////////////////////////////////////
+# TRAPS
+# ///////////////////////////////////////////////////////////////////
+
+# RETURN CODES
+#   0 : success (default)
+#   1 : fatal   (uncatched)
+#   2 : error   (catched)
+#   3 : exit    (user)
+# 130 : exit    (user)
+
+trap_exit() {
+    rm -f "${ARCH_OS_HOME}/.mirrorlist.tmp"
+    [ "$1" != "3" ] && [ "$1" != "130" ] && gum_confirm --affirmative 'Quit' --negative '' ''
+    clear && return "$1"
+}
+
+trap_error() {
+    [ "$1" != "2" ] && [ "$1" != "3" ] && [ "$1" != "130" ] && gum_fail "${BASH_COMMAND} failed ($1) in function '${2}' (line ${3})"
+    return "$1"
+}
+
+# ///////////////////////////////////////////////////////////////////
 # PROPERTIES
 # ///////////////////////////////////////////////////////////////////
 
 init_properties() {
 
-    # Init properties
-    mkdir -p "$ARCH_OS_HOME"
+    # Create home dirs
+    mkdir -p "${ARCH_OS_HOME}/config"
+    mkdir -p "${ARCH_OS_HOME}/database"
+
+    # Migrate from < 1.5.5
+    [ -f "${HOME}/.arch-os/arch-os.conf" ] && mv -f "${HOME}/.arch-os/arch-os.conf" "${ARCH_OS_HOME}/settings.conf"
+    [ -f "${HOME}/.arch-os/kitty.conf" ] && mv -f "${HOME}/.arch-os/kitty.conf" "${ARCH_OS_HOME}/config/kitty.conf"
+    [ -f "${HOME}/.arch-os/packages.db" ] && mv -f "${HOME}/.arch-os/packages.db" "${ARCH_OS_HOME}/database/packages.db"
+    [ -f "${HOME}/.arch-os/news.db" ] && mv -f "${HOME}/.arch-os/news.db" "${ARCH_OS_HOME}/database/news.db"
+
     touch "$ARCH_OS_CONF"
     source "$ARCH_OS_CONF"
 
@@ -255,8 +263,8 @@ action_help() {
     gum_title 'App'
     gum_white 'arch-os [--kitty | -k]              Open main menu'
     gum_white 'arch-os [--kitty | -k] help         Open help page'
-    gum_white 'arch-os [--kitty | -k] settings     Edit properties'
-    echo && gum_title 'Actions'
+    gum_white 'arch-os [--kitty | -k] settings     Edit properties' && echo
+    gum_title 'Actions'
     gum_white 'arch-os [--kitty | -k] check        Print package updates like checkupdates (pacman, aur, flatpak)'
     gum_white 'arch-os [--kitty | -k] notify       Notify on new package updates (pacman, aur, flatpak)'
     gum_white 'arch-os [--kitty | -k] search       Search & manage package (pacman, aur)'
@@ -541,7 +549,7 @@ action_refresh() { # Refresh mirrorlist with reflector
 
 action_downgrade() { # Downgrade packages
     if ! command -v /usr/bin/downgrade &>/dev/null; then
-        [ "$AUR_SUPPORT" = "false" ] && gum_fail "AUR Helper is missing to install downgrade!" && return 2
+        [ "$AUR_SUPPORT" = "false" ] && gum_fail "AUR Helper is missing. The package 'downgrade' can not be installed!" && return 2
         ! gum_confirm "Install Dependencies? (downgrade)" && return 3
         gum_title "Install Downgrade"
         local pkg_manager_args=()
