enhance search & logs

diff --git a/arch-os b/arch-os
--- a/arch-os
+++ b/arch-os
@@ -386,7 +386,7 @@ show_news_info() { # Show Arch Linux News
         # Helper functions
         print_news_date() { echo -n "$(<"$NEWS_DB")" | xmllint --xpath "string(//item[$1]/pubDate)" - | date -f - "+%Y/%m/%d"; }
         print_news_title() { echo -n "$(<"$NEWS_DB")" | xmllint --xpath "string(//item[$1]/title)" -; }
-        print_news_url() { echo -n "$(<"$NEWS_DB")" | xmllint --xpath "string(//item[$1]/link)" - | xargs; }
+        print_news_url() { echo -n "$(<"$NEWS_DB")" | xmllint --xpath "string(//item[$1]/link)" - | awk '{$1=$1; print}'; }
 
         # Sync db
         ! gum_spin --title 'Synchronize Database...' -- bash -c "${SELF} --sync news" && gum_fail "Synchronize Database (news) failed" && return 3
@@ -464,6 +464,22 @@ show_health_info() { # Show system health information
     # Gnome extensions count
     command -v /usr/bin/gnome-extensions &>/dev/null && gum_key_value_white "GNOME Extensions" "$(gnome-extensions list --enabled | wc -l)"
 
+    # System Failure
+    log_count=$(print_system_error_logs | wc -l)
+    if [ "$log_count" -gt "0" ]; then
+        gum_key_value_yellow "System Failure" "${log_count}"
+    else
+        gum_key_value_green "System Failure" "${log_count}"
+    fi
+
+    # Service Failure
+    service_count=$(print_service_failed | wc -l)
+    if [ "$service_count" -gt "0" ]; then
+        gum_key_value_red "Service Failure" "${service_count}"
+    else
+        gum_key_value_green "Service Failure" "${service_count}"
+    fi
+
     # Check pending updates
     local pending_updates=0
     [ -s "$UPDATES_DB" ] && pending_updates=$(wc -l <"$UPDATES_DB")
@@ -510,21 +526,6 @@ show_health_info() { # Show system health information
         gum_key_value_green "Unknown Packages" "${#unknown_pkgs[*]}"
     fi
 
-    # System Failure
-    log_count=$(print_system_error_logs | wc -l)
-    if [ "$log_count" -gt "0" ]; then
-        gum_key_value_yellow "System Failure" "${log_count}"
-    else
-        gum_key_value_green "System Failure" "${log_count}"
-    fi
-
-    # Service Failure
-    service_count=$(print_service_failed | wc -l)
-    if [ "$service_count" -gt "0" ]; then
-        gum_key_value_red "Service Failure" "${service_count}"
-    else
-        gum_key_value_green "Service Failure" "${service_count}"
-    fi
 }
 
 # ///////////////////////////////////////////////////////////////////
@@ -532,13 +533,14 @@ show_health_info() { # Show system health information
 # ///////////////////////////////////////////////////////////////////
 
 show_system_info() { # System info
-    local options user_input system_logs system_services
+    local options user_input system_logs
     gum_title "System Information"
 
     # Show system logs
     system_logs=$(print_system_error_logs)
     if [ -n "$system_logs" ]; then
-        echo -e "$system_logs" | while read -r line; do gum_log_fail "$line"; done
+        local log_counter=0
+        echo -e "$system_logs" | while read -r line; do gum_log_fail "$line" && ((log_counter++)) && [ $log_counter -gt 25 ] && echo && gum_warn "You have more than 25 Logs. Output stopped." && break; done
     else
         gum_log_info "No System Logs available"
     fi
@@ -586,13 +588,8 @@ show_system_info() { # System info
 # SEARCH
 # ///////////////////////////////////////////////////////////////////
 
+#shellcheck disable=SC2086
 show_search() { # Search & manage packages
-
-    # Helper function
-    print_package_value() {
-        local result && result="$(echo "$1" | grep -i "^${2}" | sed -E "s/^${2}\s*:\s*//" || echo "unavailable")"
-        echo "$result" | awk '{print (length($0) > 80 ? substr($0, 1, 80) "..." : $0)}' # Cut after 80 chars and print
-    }
 
     local pkg_name pkg_info_remote pkg_info_local pkg_is_aur pkg_is_installed
     while (true); do
@@ -601,18 +598,63 @@ show_search() { # Search & manage packages
         # Sync db
         [ ! -f "$PACKAGES_DB" ] && ! gum_spin --title 'Synchronize Database...' -- bash -c "${SELF} --sync packages" && gum_fail "Synchronize Database (packages) failed" && return 3
 
-        # If pkg name is null (first run) show search promt
-        [ -z "$pkg_name" ] && ! pkg_name=$(gum_filter --limit 1 --height "20" --placeholder "Search package..." <"$PACKAGES_DB") && return 2
+        # -------------------------------------------------------------------
+
+        # Select package if not exists
+        if [ -z "$pkg_name" ]; then
+
+            # Helper
+            list_results() {
+                local pkg_manager pkg_manager_result
+                pkg_manager="/usr/bin/pacman" && [ "$AUR_SUPPORT" = "true" ] && pkg_manager="/usr/bin/paru"
+                ! $pkg_manager -Ss "$1" &>/dev/null && return 1
+                pkg_manager_result="$(LANG=en_US.UTF-8 $pkg_manager -Ss "$1")"
+                local pkg_name pkg_desc
+                echo "$pkg_manager_result" | while IFS= read -r line; do
+                    if [ -z "$pkg_name" ]; then
+                        pkg_name="$(echo -e "$line" | cut -d ' ' -f 1)"
+                    else
+                        pkg_desc=$(echo "${line}" | awk '{$1=$1; print}')
+                        echo -e "${pkg_name}: ${pkg_desc}" | awk '{print (length($0) > 110 ? substr($0, 1, 110) "..." : $0)}' # Cut after 110 chars and print
+                        unset pkg_name
+                    fi
+                done
+            }
+
+            # User input
+            local user_input
+            user_input=$(gum_input --placeholder="Search Package...") || return 2
+            [ -z "$user_input" ] && gum_fail "Search was empty" && return 3
+            gum_info "Search: ${user_input}"
+
+            # Filter results
+            local filter_pkgs_results && filter_pkgs_results="$(list_results "$user_input")"
+            [ -z "$filter_pkgs_results" ] && gum_warn "No Results" && return 3
+
+            mapfile -t search_result_array < <(echo "$filter_pkgs_results")
+            ! pkg_name=$(gum_filter --limit 1 --height "20" --placeholder "Filter..." "${search_result_array[@]}") && return 2
+
+            # Set package name
+            pkg_name="$(echo "$pkg_name" | cut -d':' -f1 | cut -d'/' -f2)"
+        fi
+
+        # -------------------------------------------------------------------
+
+        # Helper function
+        print_package_value() {
+            local result && result="$(echo "$1" | grep -i "^${2}" | sed -E "s/^${2}\s*:\s*//" || echo "unavailable")"
+            echo "$result" | awk '{print (length($0) > 110 ? substr($0, 1, 110) "..." : $0)}' # Cut after 110 chars and print
+        }
 
         # Fetch general package infos
         local pkg_manager="/usr/bin/pacman" && [ "$AUR_SUPPORT" = "true" ] && pkg_manager="/usr/bin/paru"
-        pkg_info_remote="$(LANG=en_US.UTF-8 $pkg_manager -Si "$pkg_name" 2>/dev/null)" # Uninstalled
+        pkg_info_remote="$(LANG=en_US.UTF-8 $pkg_manager -Si $pkg_name)" # Uninstalled
         pkg_is_aur="false" && [ "$(print_package_value "$pkg_info_remote" "Repository")" = "aur" ] && pkg_is_aur="true"
-        pkg_is_installed="false" && /usr/bin/pacman -Q "$pkg_name" &>/dev/null && pkg_is_installed="true"
+        pkg_is_installed="false" && /usr/bin/pacman -Q $pkg_name &>/dev/null && pkg_is_installed="true"
 
         # Get installed package info
         if [ "$pkg_is_installed" = "true" ]; then
-            pkg_info_local="$(LANG=en_US.UTF-8 $pkg_manager -Qi "$pkg_name" 2>/dev/null)" # Installed
+            pkg_info_local="$(LANG=en_US.UTF-8 $pkg_manager -Qi $pkg_name)" # Installed
         fi
 
         # Print general package info
@@ -649,7 +691,7 @@ show_search() { # Search & manage packages
         echo && gum_title "Options"
         # Dynamic package entries
         local options=()
-        [ "$pkg_is_aur" = "true" ] && options+=("Show PKGBUILD")
+        [ "$pkg_is_aur" = "true" ] && [ "$AUR_SUPPORT" = "true" ] && options+=("Show PKGBUILD")
         [ "$pkg_is_installed" = "false" ] && options+=("Install")
         [ "$pkg_is_installed" = "true" ] && options+=("Remove")
         # Show downgrade entry if package is installed and not from AUR
@@ -664,23 +706,23 @@ show_search() { # Search & manage packages
             local pkg_manager_args=()
             [ "$ARCH_DOWNLOAD_TIMEOUT" = "false" ] && pkg_manager_args+=('--disable-download-timeout')
             [ "$AUR_SUPPORT" = "true" ] && [ "$AUR_REVIEW" = "false" ] && pkg_manager_args+=('--skipreview')
-            [ "$AUR_SUPPORT" = "true" ] && if /usr/bin/paru -Sq "${pkg_manager_args[@]}" "$pkg_name"; then gum_info "Done"; else gum_fail "Installing ${pkg_name} failed"; fi
-            [ "$AUR_SUPPORT" = "false" ] && if sudo /usr/bin/pacman -Sq "${pkg_manager_args[@]}" "$pkg_name"; then gum_info "Done"; else gum_fail "Installing ${pkg_name} failed"; fi
+            [ "$AUR_SUPPORT" = "true" ] && if /usr/bin/paru -Sq "${pkg_manager_args[@]}" $pkg_name; then gum_info "Done"; else gum_fail "Installing ${pkg_name} failed"; fi
+            [ "$AUR_SUPPORT" = "false" ] && if sudo /usr/bin/pacman -Sq "${pkg_manager_args[@]}" $pkg_name; then gum_info "Done"; else gum_fail "Installing ${pkg_name} failed"; fi
             ;;
         'Remove')
             ! gum_confirm "Remove?" && clear_screen && continue
-            if sudo /usr/bin/pacman -Rns "$pkg_name"; then gum_info "Done"; else gum_fail "Removing ${pkg_name} failed"; fi
+            if sudo /usr/bin/pacman -Rns $pkg_name; then gum_info "Done"; else gum_fail "Removing ${pkg_name} failed"; fi
             ;;
         'Show PKGBUILD')
             clear_screen && print_header && gum_title "PKGBUILD"
-            /usr/bin/paru -Gp "$pkg_name"
+            /usr/bin/paru -Gp $pkg_name
             ;;
         'Downgrade')
             ! gum_confirm "Downgrade?" && clear_screen && continue
-            if sudo downgrade "$pkg_name"; then gum_info "Done"; else gum_fail "Downgrading ${pkg_name} failed"; fi
+            if sudo downgrade $pkg_name; then gum_info "Done"; else gum_fail "Downgrading ${pkg_name} failed"; fi
             ;;
         'Done') return 2 ;;
-        *) gum_fail "Action '${user_input}' not available" && return 3 ;;
+        *) unset pkg_name && gum_fail "Action '${user_input}' not available" && return 3 ;;
         esac
         gum_confirm_continue
         clear_screen
@@ -1005,9 +1047,9 @@ gum_red() { gum_style --foreground "$COLOR_RED" "${@}"; }
 
 # Print
 gum_title() { gum join "$(gum_purple --bold "// ")" "$(gum_purple --bold "${*}")"; }
-gum_info() { gum join "$(gum_green --bold " • ")" "$(gum_green --bold "${*}")"; }
-gum_warn() { gum join "$(gum_yellow --bold " • ")" "$(gum_yellow --bold "${*}")"; }
-gum_fail() { gum join "$(gum_red --bold " • ")" "$(gum_red --bold "${*}")"; }
+gum_info() { gum join "$(gum_green --bold " • ")" "$(gum_white --bold "${*}")"; }
+gum_warn() { gum join "$(gum_yellow --bold " • ")" "$(gum_white --bold "${*}")"; }
+gum_fail() { gum join "$(gum_red --bold " • ")" "$(gum_white --bold "${*}")"; }
 gum_mesg() { gum join "$(gum_white --bold " • ")" "$(gum_white --bold "${*}")"; }
 gum_content() { gum join "$(gum_white " • ")" "$(gum_white "${*}")"; }
 gum_content_strong() { gum join "$(gum_green " • ")" "$(gum_white --bold "${*}")"; }
